### ISSUE TITLE
Allow phases

### ISSUE THREAD

**Issue by slowe** [aperiosoftware/timeseries.js#10]
Allow phases rather than times. Currently we've defaulted to a time-based axis so we'll need to know not to do that. Perhaps with a consistent column heading e.g. `phase_unity`.

**Comment by slowe** [comment]
@astrofrog Unless I've forgotten something, this is the same as having an x-axis as a number rather than time isn't it? In the JSON you can use:
```
"scales": [{
   ...
   "type":"linear"
   ...
},{
   ...
}]
```

to allow the axis to be a number. I need to hide the *Date format* dropdown box in the menu in cases where it isn't a date or relative date.

**Comment by astrofrog** [comment]
Yes that is my recollection too 👍

**Comment by slowe** [comment]
Here's [a test](https://aperiosoftware.github.io/timeseries.js/examples/phase). The default view shows the time. The second view shows phase.

**Comment by slowe** [comment]
![timeseries](https://user-images.githubusercontent.com/299787/54289189-a3ff1d00-45a0-11e9-8a9d-d6583b719c38.png)
![timeseries-phase](https://user-images.githubusercontent.com/299787/54289211-ae211b80-45a0-11e9-870f-1b0ad96e5966.png)
Here's a couple of screen shots of the example.
