### ISSUE TITLE
Two-finger scrolling speed

### ISSUE THREAD

**Issue by astrofrog** [aperiosoftware/timeseries.js#18]
At the moment, using two-finger scrolling to zoom leads the plot to zoom in/out at a speed that doesn't appear to be related to the physical scrolling speed - that is, as long as I'm scrolling e.g. up, the plot zooms in at a constant rate. It would be nice to adjust this so that the zooming is proportional to scrolling speed.

**Comment by slowe** [comment]
@astrofrog Is this now behaving as you'd expect?

**Comment by astrofrog** [comment]
Yes, it's great now, thanks!
