### ISSUE TITLE
Sideways shift when zooming in/out

### ISSUE THREAD

**Issue by astrofrog** [aperiosoftware/timeseries.js#19]
I noticed a subtle issue when zooming in/out - at some of the zoom steps it looks like the data shifts sideways. I've tried to record this in a GIF:

![side_shift](https://user-images.githubusercontent.com/314716/48428949-00be0880-e764-11e8-9fd3-094f895cfa88.gif)

In the fourth frame, the data ends up being behind the cursor for one frame, then shifts back to the left after. This makes the zoom seem a bit 'jumpy' when using it at a normal speed.

**Comment by astrofrog** [comment]
Actually now I look at the animation, I see more clearly that the y axis is shifting from right to left as well.

**Comment by astrofrog** [comment]
I should add, this is with Chrome on MacOS X, when looking at Example 1 here: https://aperiosoftware.github.io/timeseries.js/

**Comment by slowe** [comment]
The reason the y-axis shifts is because the y-axis label sizes change size. In the example they gain a significant figure.

**Comment by slowe** [comment]
@astrofrog I'm not sure what the best behaviour would be here. If the axis location stays fixed the labels start to obscure the axis title and, potentially, head off the left of the screen becoming unreadable.

**Comment by astrofrog** [comment]
@slowe - I'll investigate what other tools do. One option is to allow more space to start with and then if we run out of space, to play with the font size of the tick labels.

**Comment by astrofrog** [comment]
So thinking about this a bit more, I think the issue is that this happens for every order of magnitude - maybe it would be less noticeable if we left enough space for the tick labels so that this only happens every few orders of magnitude?

**Comment by slowe** [comment]
There are now a few precision errors for "zero". 
![index](https://user-images.githubusercontent.com/299787/49750841-d3517580-fca3-11e8-9869-1bb15080767a.png)

**Comment by slowe** [comment]
@slowe If the range is big, check the labels for tiny numbers due to precision problems

**Comment by slowe** [comment]
@astrofrog Could you review this? It now passes [all our axis formatting tests](https://aperiosoftware.github.io/timeseries.js/tests/format). But feel free to add more tests.

**Comment by slowe** [comment]
@astrofrog I think this is now resolved. If any of the axes labels are *not* exponential notation we do these steps:
1. calculate the length of the integer+decimal part of each label
1. round that up to the nearest multiple of 3
1. build a dummy label of the larger length
1. use the width of the dummy label.

**Comment by astrofrog** [comment]
Here are some examples of remaining issues:

![screenshot 2019-01-15 at 14 05 08](https://user-images.githubusercontent.com/314716/51185325-b75a7880-18ce-11e9-9581-c4d62ec25c41.png)
![screenshot 2019-01-15 at 14 05 45](https://user-images.githubusercontent.com/314716/51185328-b88ba580-18ce-11e9-9762-0cdb666f1972.png)
