### ISSUE TITLE
Have a way to specify relative instead of absolute times in the JSON

### ISSUE THREAD

**Issue by astrofrog** [aperiosoftware/timeseries.js#20]
It would be good to have a way to specify relative times (with an arbitrary epoch which isn't specified) in the JSON file, as floating point values in e.g. seconds. We use relative times on the Python side to represent folded time series for example.

Note that this is separate from https://github.com/aperiosoftware/timeseries.js/issues/10 which is for dimensionless phases.

**Comment by slowe** [comment]
@astrofrog If the aim here is to display a formatted time (rather than just numbers), won't it need an epoch?

**Comment by astrofrog** [comment]
There are specific cases where we really just want a relative time, e.g. 10 hours since the start of the observations, or some time from the peak of the event. In this case I think we'd want to format as decimals numbers in some units (e.g. seconds, minutes, or hours) not as normal date/times.

**Comment by slowe** [comment]
I've made a test page to test formatting of relative times. Please add test cases https://aperiosoftware.github.io/timeseries.js/tests/relativetime

**Comment by slowe** [comment]
We are thinking of adding a `"_date": "relative"` key in the top of the JSON file. We can use it in our code to set the list of drop down options for date format. We'll have different options depending on if we are `relative` or not.

Advantages:
- doesn't cause any warnings in the online Vega editor
- the leading underscore means it is unlikely for Vega to add this key in the future

For relative dates, in the xaxis `scale` definition we could set the `type` to `linear` rather than `date`. That way Vega displays the xaxis labels as numbers. We will use the `_date` key to treat it as a time in our code.

**Comment by slowe** [comment]
I've altered the keywords to use for setting date formats.

- ***Absolute date*** - set the x-axis type to `time`/`utc` and then set a variable `_xtype` to `date`. Each view can have a different `_xtype` set. You can choose the date format of to use by setting `_xformat` to the appropriate key e.g. `default`, `locale`, `jd`, `mjd`, `tjd`.
- ***Relative date*** - set the x-axis type to `linear` and then set a variable `_xtype` to `date`. Each view can have a different `_xtype` set. You can choose the date format of to use by setting `_xformat` to the appropriate key e.g. `default`, `relative`.
- ***Phase*** - set the x-axis type to `linear` and then set `_xtype` to `phase`.

See [the views in this example](https://aperiosoftware.github.io/timeseries.js/examples/phase).

**Comment by slowe** [comment]
OK, after discussion we are changing this to explicitly specifying the input column format and the output display format (the default selected on the x-axis formatting dropdown list). To keep things tidy we will put non-VEGA x-axis options in an `_x` object like this:

```JSON
{
  "input": "iso",
  "output": "auto"
}
```

`input` defines the input data format and can be one of `phase`, `seconds`, `jd`, `mjd`, `tjd`, `unix`, `iso`.
`output` defines the default selected output type. The options are:

1. `auto`, `jd`, `mjd`, `tjd`, `unix`, `iso`, `locale` for absolute times;
2. `auto`, `seconds` for relative times;
3. `degrees`, `radians`, `unity` for phases.

Views will be able to have an `_x` set.

**Comment by slowe** [comment]
Slight modification to the above... change the `x` in extend to:
```
"_extend": {
  "scales": [{
    "name": "xscale",
    "input": "iso",
    "output": "auto"
  }]
}
```
Where the `name` is set to `xscale` and we will treat this as adding our bonus properties to the corresponding `scale`.
