### ISSUE TITLE
Separate layers from other settings?

### ISSUE THREAD

**Issue by astrofrog** [aperiosoftware/timeseries.js#22]
I wonder if we might want two menus instead of one - one the controls the layers that are shown/hidden, and the other one which has the other/more advanced settings? If we do this, the icon for the layers could be the current one, and the one for the menu could be e.g. a gearwheel?

**Comment by slowe** [comment]
@astrofrog We can have two menus. Are you imagining this being done in a way that increases the number of always-visible items? I agree that the layer controls are thematically distinct from the other settings. I'd been imagining making that distinction with a sub menu (perhaps as up to 4 icon-based tabs) so as not to add more visual clutter to the initial/main view.

**Comment by slowe** [comment]
@astrofrog Here's a version that uses sub menus with icon-based tabs.
![screenshot_2018-11-27 timeseries js library](https://user-images.githubusercontent.com/299787/49088404-1eee3300-f251-11e8-8b24-76d417a5b175.png)

**Comment by slowe** [comment]
The menu has evolved. Each marker group has a bigger click area and there are representative icons for each. The layers tab is the default tab when the menu is opened. 
![screenshot_2019-01-29 timeseries js library](https://user-images.githubusercontent.com/299787/51941607-ee6f7480-240c-11e9-829e-cce9507db7b2.png)
