### ISSUE TITLE
Rendering on High DPI displays

### ISSUE THREAD

**Issue by astrofrog** [aperiosoftware/timeseries.js#24]
Currently the fonts and lines look a little fuzzy on a retina display:

<img width="1064" alt="screen shot 2018-11-27 at 11 50 07" src="https://user-images.githubusercontent.com/314716/49080217-d166cb80-f23a-11e8-9582-5569291a50b1.png">

compared with the text in the caption. Is there any way to detect high resolution displays and increase the resolution of the canvas?

**Comment by slowe** [comment]
@astrofrog Probably. My guess would be that doubling the pixel resolution will cause knock-on problems interpreting mouse/cursor positions. This will be hard for me to test as I don't have a retina display.

**Comment by astrofrog** [comment]
@slowe - I can lend you my laptop this afternoon for a little as I have a couple of phone calls I need to make

**Comment by astrofrog** [comment]
There's still something not quite right - the axes and fonts look fine but the actual data is still fuzzy:

<img width="366" alt="screen shot 2018-12-17 at 13 13 52" src="https://user-images.githubusercontent.com/314716/50089422-b49c3300-01fd-11e9-93c8-72281b6f747d.png">

@slowe - if you could make a very minimal example that draws a letter and a diagonal line, I can try and then debug locally.

**Comment by slowe** [comment]
Check https://aperiosoftware.github.io/timeseries.js/tests/line for a test of lines and text.

**Comment by astrofrog** [comment]
Thanks! Could you include a couple of circular markers too?

**Comment by astrofrog** [comment]
Very strange, for some reason those look nice and crisp. I'll try and investigate over the holidays.

**Comment by astrofrog** [comment]
Another issue is that sometimes things get out of sync and the canvas ends up being too large:

<img width="1224" alt="screen shot 2018-12-18 at 14 22 12" src="https://user-images.githubusercontent.com/314716/50160146-71f75b00-02d0-11e9-8e51-8a260ae3be97.png">

**Comment by astrofrog** [comment]
Here's a slow motion of it happening, note the warning in the JS console:

![timeseries](https://user-images.githubusercontent.com/314716/50167005-0f0dc000-02e0-11e9-945a-040a07ea5579.gif)

**Comment by slowe** [comment]
Ah. So it is due to a page resize event.

**Comment by astrofrog** [comment]
Ah that makes sense, it also happens if I open the javascript console which changes the page size.

**Comment by astrofrog** [comment]
This has been fixed in https://github.com/aperiosoftware/timeseries.js/commit/5566daeb9e4cfb6402cff582654c889ecfb7e66a - thanks @slowe!
