### ISSUE TITLE
If a CSV file is missing, graph still looks like it's loading

### ISSUE THREAD

**Issue by astrofrog** [aperiosoftware/timeseries.js#26]
We should maybe have a way to indicate visually that an error has happened - otherwise if a CSV file is not found it looks like the graph is loading forever:

<img width="559" alt="screenshot 2019-01-04 at 15 04 01" src="https://user-images.githubusercontent.com/314716/50694576-219f2d80-1032-11e9-891e-53de1bc4630c.png">

**Comment by slowe** [comment]
A graph can be loading multiple csv files. Do we want to make it remove the loading animation and show an error if *any* of them can't load?

**Comment by astrofrog** [comment]
@slowe - yes I think we should error if any of them are missing

**Comment by slowe** [comment]
Here's a preview of what the new behaviour looks like https://aperiosoftware.github.io/timeseries.js/tests/loadfail
