### ISSUE TITLE
Document supported marks and options

### ISSUE THREAD

**Issue by astrofrog** [aperiosoftware/timeseries.js#34]
Now that I'm working on the Python -> JSON implementation, it would be helpful to have somewhere a list of the subset of marks and attributes for marks that we support. Would this be easy to produce?

**Comment by slowe** [comment]
@astrofrog This would definitely be useful. I'll make it.

**Comment by slowe** [comment]
There is now [documentation about marks](https://aperiosoftware.github.io/timeseries.js/docs/marks) with examples.

**Comment by astrofrog** [comment]
Thanks! I'll try and make sure I support all these from the Python side.
