### ISSUE TITLE
Styling issues when embedding in aas-timeseries documentation

### ISSUE THREAD

**Issue by astrofrog** [aperiosoftware/timeseries.js#36]
@slowe - this is just to let you know that the example I showed you before is now live in case you want to debug the styling issues you noticed:

https://aas-timeseries.readthedocs.io/en/latest/getting_started.html

(it takes a few seconds to load)

**Comment by slowe** [comment]
@astrofrog Read The Docs was adding its default styles (padding/margins etc) to elements. Hopefully I've sorted that out.

**Comment by astrofrog** [comment]
Thanks! Will test out shortly.

**Comment by astrofrog** [comment]
I think this should now be fixed!
