### ISSUE TITLE
Stop loading if JSON is invalid

### ISSUE THREAD

**Issue by astrofrog** [aperiosoftware/timeseries.js#38]
Currently if there are issues in the JSON, the widget is stuck on the 'loading' progress bar:

<img width="1391" alt="screenshot 2019-01-29 at 14 14 30" src="https://user-images.githubusercontent.com/314716/51914256-4e93f580-23d0-11e9-9a3e-e45744688a38.png">

It would probably make sense to just show a generic error message if any issues occur during parsing.

**Comment by slowe** [comment]
The example given above renders now. ![screenshot_2019-02-05 timeseries js library 4](https://user-images.githubusercontent.com/299787/52277206-046cc000-294c-11e9-9941-1cd924ad7ed2.png)
