### ISSUE TITLE
Issue with area if lower y value is zero

### ISSUE THREAD

**Issue by astrofrog** [aperiosoftware/timeseries.js#41]
I tried plotting a time series where the area shown should go from 0 to 4 in the 5th time bin, but instead it looks like this is being treated as empty and there is a break in the area:

<img width="416" alt="screenshot 2019-01-29 at 23 17 59" src="https://user-images.githubusercontent.com/314716/51947288-3c3fa900-241c-11e9-906c-f7e6520202e9.png">

I can provide a JSON file if needed.

**Comment by slowe** [comment]
I was mistakenly testing for a non-zero value rather than an undefined value. Does it work for your example now?

**Comment by astrofrog** [comment]
@slowe - I'm still seeing issues - here's the JSON file: https://gist.github.com/astrofrog/512baa0808765f78a527e693b10261fd

**Comment by slowe** [comment]
![screenshot_2019-02-05 timeseries js library 1](https://user-images.githubusercontent.com/299787/52275592-e4d39880-2947-11e9-9f5f-0c5993740363.png)
I'm going to class this as fixed.
