### ISSUE TITLE
Aesthetic issues in legend

### ISSUE THREAD

**Issue by astrofrog** [aperiosoftware/timeseries.js#42]
I noticed a few things that could be fine tuned in the list of layers:

<img width="618" alt="screenshot 2019-01-30 at 00 10 48" src="https://user-images.githubusercontent.com/314716/51949189-85472b80-2423-11e9-8ea5-9c0d75fa81a4.png">

* The icons don't seem to be HiDPI even when the actual plot is
* The icon for horizontal rules is a vertical line - if possible it would be good to make it horizontal (the 'baseline flux one in this case')
* For the vertical and horizontal range the icons are empty - I'm using rect for these, maybe I should be using area?
* Could the 'T' in the text label icon be centered vertically?

JSON file: https://gist.github.com/astrofrog/d5c6ee538870a0ed1452bc1e70ec6deb

**Comment by slowe** [comment]
![screenshot_2019-02-05 timeseries js library 3](https://user-images.githubusercontent.com/299787/52276675-b6a38800-294a-11e9-9ffd-2d75a1b349ba.png)
- [x] The icons don't seem to be HiDPI even when the actual plot is
- [x] The icon for horizontal rules is a vertical line - if possible it would be good to make it horizontal (the 'baseline flux one in this case')
- [x] For the vertical and horizontal range the icons are empty - I'm using rect for these, maybe I should be using area?
- [x] Could the 'T' in the text label icon be centered vertically?
