### ISSUE TITLE
Bug when domain is defined on main plot but not view

### ISSUE THREAD

**Issue by astrofrog** [aperiosoftware/timeseries.js#44]
I'm having issues with the following JSON file:

https://gist.github.com/astrofrog/4f027054afc47964a37cd9385d8ead37

The error I'm getting is ``Unexpected token u in JSON at position 0``

**Comment by slowe** [comment]
Having fixed #43, is this still an issue? When I try that JSON I now get this:
![screenshot_2019-02-05 timeseries js library](https://user-images.githubusercontent.com/299787/52270872-147ba400-293a-11e9-8e35-a93781fc86db.png)

**Comment by astrofrog** [comment]
This works now, thanks!
