### ISSUE TITLE
Provide public API to list views and cycle through them

### ISSUE THREAD

**Issue by astrofrog** [aperiosoftware/timeseries.js#46]
For the purposes of automatically saving static versions of figures, it would be nice to have a way to get a list of available views (if possible with some way of getting the names of the views) and then a way to select the active view.

**Comment by slowe** [comment]
Say you've created a `figure`:

```javascript
// Create a TimeSeries object using an external, Vega-compatible, JSON file
figure = TimeSeries.create("examples/data/lightcurve2.json");
				
// Attach the TimeSeries to a DOM element
figure.initialize(document.getElementById('figure1'));
```
You can get the array of view objects using:

```javascript
views = figure.getViews();
```
Which returns an array e.g. `Array(3) [{...},{...},{...}]` where each item in the array is of the form:

```javascript
{
​​  name: "default",                // Unique ID for this view
  title: "Default",               // Value displayed to the end user in the view menu
  description: "The initial view" // Extra descriptive text
​​}
```
You can set a view using:
```javascript
figure.setView(x)
```
where `x` is the index of the view you wish to switch to.
