### ISSUE TITLE
Issue when default view doesn't have domain defined but view does

### ISSUE THREAD

**Issue by astrofrog** [aperiosoftware/timeseries.js#47]
If I create a figure that has no domain specified but with a view that does, when I change to the view the domain changes, but if I change back to the default view, the limits don't reset to the ones that were chosen automatically when showing the figure at the start. I think it would make sense to re-compute the default in this case.

**Comment by astrofrog** [comment]
I'm not sure if this is related, but in this case Zoom to Data also doesn't work when in the view with the domain defined.

**Comment by slowe** [comment]
Part of the issue here is that the initial view *should* have a domain defined. Vega doesn't like having no domain; our implementation is (on initial load) being more forgiving than Vega because no domain is set. For [this example](https://aas-timeseries.readthedocs.io/en/latest/views.html) you might want to add:
```JSON
"scales": [{
  "name": "xscale",
  "type": "time",
  "range": "width",
  "zero": false,
  "domain": {
    "data": "1719fd71-44c7-4478-aa82-e6844fec45a5",
    "field": "time"
  }
},{
  "name": "yscale",
  "type": "linear",
  "range": "height",
  "zero": false,
  "domain":{
    "data": "1719fd71-44c7-4478-aa82-e6844fec45a5",
    "field": "sap_flux"
  }
}]
```
That way, when switching back to the initial view, there is a domain to over-write the domain set by the second view. This also means that the initial view shows up in the online Vega Editor.

**Comment by astrofrog** [comment]
Ok, will do - just out of curiosity, is there a smart way of saying that the initial view should be a little larger than the range of values? (so that datapoints don't go right to the edge of the axes)

**Comment by slowe** [comment]
It seems Vega allows for padding within an axis by adding `padding` and a pixel value to a scale. In implementing it I found a bug in the object extending code so I've fixed that too. You'd add padding something like this:

```
"scales": [{
			"name": "xscale",
			"type": "utc",
			"range": "width",
			"zero": false,
			"padding": 18,
			"domain": [{"signal":"datetime(2018,9,29,13,53,20)"},{"signal":"datetime(2018,9,29,13,53,24)"}]
		},{
			"name": "yscale",
			"type": "linear",
			"range": "height",
			"zero": false,
			"padding": 9,
			"domain": [0.965,1.01]
		}],
```

The [basic example](https://aperiosoftware.github.io/timeseries.js/basic) now has padding on the default view.

**Comment by slowe** [comment]
The "Zoom to data" button should probably be a "reset view" button instead.
