### ISSUE TITLE
big.js causing issues when using timeseries.js in webpack

### ISSUE THREAD

**Issue by astrofrog** [aperiosoftware/timeseries.js#52]
At the moment we can't use the latest version of timeseries.js in Jupyter notebooks because somehow big.js isn't getting picked up correctly (this may be a big.js issue: https://github.com/MikeMcl/big.js/issues/95).

@slowe - I'll show you in person next time we meet

**Comment by astrofrog** [comment]
I've set up a simple webpack example to demonstrate the issue in this branch:

https://github.com/astrofrog/timeseries.js/tree/with-webpack/webpack

If you follow the instructions in the README this will create a single ``main.js`` file with all the JS/CSS. If you then try and open the dist/index.html file, the output will look like:

<img width="808" alt="Screenshot 2019-04-05 at 10 48 45" src="https://user-images.githubusercontent.com/314716/55619383-77e64e80-5790-11e9-9f30-3dff358f5dcd.png">

and the JS console shows:

```
ERROR Graph: Unable to find big.js 
```

This is causing the Jupyter widget to no longer work, so it's reasonably high priority to fix this. Maybe we can look into it together in person.

**Comment by slowe** [comment]
The error message complains about not finding `big.js` which wasn't included in the repo; `big.min.js` was. I've both added `big.js` and updated `big.min.js` from v5.2 to v5.2.2. It might be that there was a bug in version 5.2 or it might be that the minified version is messing up webpack. See if either using `big.js` or the new version of `big.min.js` makes a difference.

**Comment by astrofrog** [comment]
@slowe - I finally figured out the solution, which is that Big needs to be exported globally in my ``index.js`` file by using ``self``:

https://github.com/astrofrog/timeseries.js/commit/6db2e7fc56ad0e063b81b732b95f31d7045e6760

This works with the minified ``big.js`` file so we can continue to use that rather than the full one.
