### ISSUE TITLE
UK data not in default view in petition example

### ISSUE THREAD

**Issue by astrofrog** [aperiosoftware/timeseries.js#53]
In the following page:

https://aperiosoftware.github.io/timeseries.js/examples/241584

One has to zoom out a lot to see the UK data. Maybe this would be a good use case of having a view for non-UK countries but showing and setting the limits for all countries by default?

**Comment by slowe** [comment]
@astrofrog Sorry, I created this example specifically to be zoomed in on FR, AU, and US data by default as the purpose was to look at the non-UK view (but not remove the UK data). My plan had been to create a secondary view that was zoomed to everything; I just hadn't got around to it.
