### ISSUE TITLE
Starting to pan/zoom should interrupt drawing

### ISSUE THREAD

**Issue by astrofrog** [aperiosoftware/timeseries.js#54]
I'm not sure how easy this is to do so not super high priority, but if I go to an example with many points such as the goes example, and if I pan and mouse up, then I have to wait until the points are drawn before starting panning again. It would be nice if starting a panning/zooming event interrupts any existing drawing and starts panning/zooming immediately.

**Comment by slowe** [comment]
It isn't easy and it comes with trade offs as it'll probably require making everything slightly slower to draw by splitting the drawing up into chunks like was done with loading data from a file.

**Comment by astrofrog** [comment]
This is now better than it was, but there are still some issues with the view jumping around

**Comment by astrofrog** [comment]
Looks like the issue of jumping around is now fixed too - thanks @slowe !
