### ISSUE TITLE
Text not clipped to axes in example on home page

### ISSUE THREAD

**Issue by astrofrog** [aperiosoftware/timeseries.js#60]
Just a minor visual issue on the front page - the A5 label isn't clipped when it falls outside of the axes:

![Screenshot from 2019-04-26 10-44-20](https://user-images.githubusercontent.com/314716/56799252-7ac4e400-6810-11e9-9588-3306d8ec455e.png)

**Comment by slowe** [comment]
:) This was a deliberate test from a while ago (it doesn't have `"clip": true` set). However, this example now has a different purpose so I'll update it.
