### ISSUE TITLE
Issue with plot hanging

### ISSUE THREAD

**Issue by astrofrog** [aperiosoftware/timeseries.js#61]
I'm trying to add markers in a view, and this is causing the figure to hang with the loading animation. The JSON and CSV files can be found here:

https://gist.github.com/astrofrog/500ced936516763b70854641ec749a16

**Comment by slowe** [comment]
This seems to mostly be due to an `_extend->mark` referencing a `from->data` that doesn't exist in the file e.g. `62a5a561-c30a-4047-9a78-5c55ab563031`. I should add an error message and make it so that this doesn't hang things during the initial render.

**Comment by slowe** [comment]
It should no longer hang and there are errors thrown. Here's the Gist example with the console open. 
![Screen Shot 2019-05-20 at 09 56 20](https://user-images.githubusercontent.com/299787/58009075-922c7f80-7ae5-11e9-9a8d-d9f9a8bdb7a0.png)
