### ISSUE TITLE
Add a credit line with link

### ISSUE THREAD

**Issue by astrofrog** [aperiosoftware/timeseries.js#62]
We need to indicate somewhere what package was used to produce it and somehow mention the AAS. One or some of the words could link to (for now) the timeseries.js homepage, and later to a page on the AAS website that gives details about the project. Example:

*Figure produced with the AAS timeseries.js package*

We should also mention the package version somewhere.

**Comment by slowe** [comment]
Done. It isn't easy to make it float right because I'm using a hack with `flex` to expand an empty item at the end of the menu.
