### ISSUE TITLE
Show warning when field does not exist

### ISSUE THREAD

**Issue by astrofrog** [aperiosoftware/timeseries.js#63]
In the following example, I would have expected a warning because the field used in the marks doesn't actually exist in the data:

https://gist.github.com/astrofrog/fde62b6802be3727a3ac4022e2c84d04

**Comment by slowe** [comment]
There are now error messages for missing fields. Is this the sort of thing you were after?
![Screen Shot 2019-05-14 at 12 11 12](https://user-images.githubusercontent.com/299787/57693572-75a1ca80-7641-11e9-9c5b-525f676d7505.png)

**Comment by astrofrog** [comment]
Yes perfect!
