### ISSUE TITLE
Add callback to setView

### ISSUE THREAD

**Issue by astrofrog** [aperiosoftware/timeseries.js#64]
The initialize method has a callback for when the figure is ready - can we add one for setView, or is that method blocking? Basically I need to know in my Python code once the view has actually updated.

**Comment by slowe** [comment]
Because the drawing now sometimes uses setTimeout (to allow cancelling) I guess you can't just use the return from `setView`. So, I've added the option to send an extra object to `setView` with a `callback` property set to a function. Does this do the job? e.g

```
ex1.setView(1,{
    'callback': function(){
        console.log('Done');
    }
});
```

**Comment by astrofrog** [comment]
I'll try this out, thanks!

**Comment by astrofrog** [comment]
Works, thanks!
