### ISSUE TITLE
initialize callback being called before figure is actually ready

### ISSUE THREAD

**Issue by astrofrog** [aperiosoftware/timeseries.js#65]
I'm relying on the callback in the initialize method to tell me when I can save a screenshot of the figure, but unfortunately this doesn't seem to be working, as it seems to get called too soon:

![test png](https://user-images.githubusercontent.com/314716/57130452-66916180-6d91-11e9-834a-9fb9f3226681.png)

**Comment by slowe** [comment]
As of commit 0d21f447175099501cfd64a03376704f30a61a5f this should be fixed. I've also removed the log message that had been added previously (e.g. `Finished processing example1`) as you can do this within the callback with your own message.

**Comment by astrofrog** [comment]
Thanks!
