### ISSUE TITLE
Time zone issue

### ISSUE THREAD

**Issue by astrofrog** [aperiosoftware/timeseries.js#66]
Not the kind of issue you want to read, but I'm having an issue on Windows. Note that the example on the main timeseries.js home page works fine, so I'm not sure what's going on here. If I try and load the following files:

https://gist.github.com/astrofrog/43cf92e8456212c97d3b5fe3697bdf0c

Some of the layers (it seems to be the ones that depend on the actual data) appear to be missing, but there are no errors/warnings in the console:

<img width="300" alt="figure" src="https://user-images.githubusercontent.com/314716/57153076-35616300-6d8a-11e9-83b9-0f4f2b5dafe9.png">

It looks like ``CSV2JSON`` parses the file correctly - this is ``newdata`` at the end of that function:

```
[object Array]: [Object, Object, Object, Object, Object]

0: Object
error: 1
flux: 1
time: "2016-03-22T12:30:31.000"

__proto__: Object


1: Object
error: 2
flux: 2
time: "2016-03-22T12:30:34.000"

__proto__: Object

2: Object
error: 3
flux: 3
time: "2016-03-22T12:30:37.000"

__proto__: Object

3: Object
error: 4
flux: 4
time: "2016-03-22T12:30:40.000"

__proto__: Object

4: Object
error: 5
flux: 5
time: "2016-03-22T12:30:43.000"

__proto__: Object
length: 5
```

so I'm not sure what could be going on here. This is with Microsoft edge.

On MacOS X, the output looks like:

![figure](https://user-images.githubusercontent.com/314716/57153263-b55cec80-6dcd-11e9-92fb-9fd2960ac79a.png)

**Comment by astrofrog** [comment]
Interestingly this happens on Firefox on Windows too, so it's not specific to Edge - it's specific to Windows.

**Comment by astrofrog** [comment]
If I only include the line data in the JSON file, this.marks[idx] in ``addMarks`` in ``graph.js`` is:

```
data: Array

0: Object
error: 1
flux: 1
time: 1458675031

__proto__: Object

1: Object
error: 2
flux: 2
time: 1458675034

__proto__: Object


2: Object
error: 3
flux: 3
time: 1458675037

__proto__: Object

3: Object
error: 4
flux: 4
time: 1458675040

__proto__: Object

4: Object
error: 5
flux: 5
time: 1458675043

__proto__: Object
```

on Windows and:

**Comment by astrofrog** [comment]
Ah an indeed the data is offset by 7 hours, not completely missing. But the fact it's off by an integer number of hours suggests to me it's time zone related somehow.

My Windows machine was accidentally set to be in Pacific time (GMT - 8). If I change the time zone of the computer to the correct one, it shifts the data. I need to put it on UTC + 0 for the data to be in the right place.

**Comment by astrofrog** [comment]
Oh in fact I can reproduce the issue on MacOS X if I just change the time zone 🤦‍♂

**Comment by astrofrog** [comment]
I think this might be because I'm storing the dates without a trailing Z

**Comment by slowe** [comment]
Yep, ISO dates (with no times) get interpreted as UTC. However, when times *are* included without timezone, it is [assumed to be in the local time zone](https://en.wikipedia.org/wiki/ISO_8601#Times).
