### ISSUE TITLE
ReadTheDocs out-of-date

### ISSUE THREAD

**Issue by slowe** [aperiosoftware/timeseries.js#69]
The ["Setting up pre-defined views"](https://aas-timeseries.readthedocs.io/en/latest/views.html) examples in ReadTheDocs seem to break when changing the views. This is probably because we changed some things in the JSON (I think your JSON is up-to-date) but ReadTheDocs is using timeseries.js v0.0.16 rather than v0.0.18.

**Comment by slowe** [comment]
This is related to #36

**Comment by astrofrog** [comment]
Looks like this is now up to date
