### ISSUE TITLE
Add support for decimal minutes/hours/days/years formats for relative times

### ISSUE THREAD

**Issue by astrofrog** [aperiosoftware/timeseries.js#73]
At the moment, it's possible to output the labels for the x axis as decimal values in seconds (without e.g. hh:mm:ss style formatting). It would be nice to extend this to allow formatting in e.g decimal minutes, or hours, without any kind of automated switching between them.

**Comment by slowe** [comment]
Added `hours`, `days`, and `years`.

**Comment by astrofrog** [comment]
Thanks!
